apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  DB_HOST: postgresql-service
  DB_PORT: "5432"
  DB_NAME: "users-database"
  DB_USERNAME: "ahmad"
  DB_PASSWORD: "POSTGRES_PASSWORD"