# This file is a kubernetes congiguration file that defines the service for the postgresql database defined and deployed in `postgresql-deployment.yaml`. 
# The service is used to expose the database to the other services in the cluster.

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432